DROP SCHEMA EST_III;

CREATE SCHEMA EST_III;

USE EST_III;

CREATE TABLE IF NOT EXISTS CLIENTES (
COD_CLIENTE INT PRIMARY KEY,
CNPJ VARCHAR(14) NOT NULL,
RAZAO_SOCIAL VARCHAR(255) NOT NULL,
RAMO_ATIVIDADE VARCHAR(100),
DATA_CADASTRAMENTO_CLI DATE, 
TELEFONE_CLI VARCHAR(15),
CIDADE_CLI VARCHAR(50),
ESTADO_CLI VARCHAR(50),
PAIS_CLI VARCHAR(50),
NUMRUA_CLI VARCHAR(10),
BAIRRO_CLI VARCHAR(50),
COMPLEMENTO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS (
MATRICULA_EMPREGADOS INT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
TEL_EMPREGADOS VARCHAR(15),
CARGO_EMPREGADOS VARCHAR(70),
SALARIO_EMPREGADOS DECIMAL(10,2),
DATA_ADMISSAO DATE NOT NULL,
QUALIFICACOES_EMPREGADOS TEXT,
CIDADE_EMPREGADOS VARCHAR(50),
ESTADO_EMPREGADOS VARCHAR(50),
PAIS_EMPREGADOS VARCHAR(50),
NUMRUA_EMPREGADOS VARCHAR(10),
BAIRRO_EMPREGADOS VARCHAR(50),
COMPLEMENTO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS EMPRESAS (
CNPJ VARCHAR(14) PRIMARY KEY,
RAZAO_SOCIAL VARCHAR(255) NOT NULL,
RAMO_ATIVIDADE VARCHAR(100),
TELEFONE_EMPR VARCHAR(15),
PESSOA_CONTATO VARCHAR(30),
CIDADE_EMPR VARCHAR(50),
ESTADO_EMPR VARCHAR(50),
PAIS_EMPR VARCHAR(50),
NUMRUA_EMPR VARCHAR(10),
BAIRRO_EMPR VARCHAR(50),
COMPLEMENTO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
CNPJ VARCHAR(14) PRIMARY KEY,
RAZAO_SOCIAL VARCHAR(255) NOT NULL,
RAMO_ATIVIDADE VARCHAR(100),
TELEFONE_FORN VARCHAR(15),
PESSOA_CONTATO VARCHAR(30),
CIDADE_FORN VARCHAR(50),
ESTADO_FORN VARCHAR(50),
PAIS_FORN VARCHAR(50),
NUMRUA_FORN VARCHAR(10),
BAIRRO_FORN VARCHAR(50),
COMPLEMENTO VARCHAR(255)
); 

CREATE TABLE IF NOT EXISTS TIPOS_ENDERECO (
COD_END INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS TIPOS_COMPONENTE (
COD_COMPONENTE INT PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
DESCRICAO TEXT
);

CREATE TABLE IF NOT EXISTS ENDERECO (
ID INT PRIMARY KEY,
LOGRADOURO VARCHAR(255) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
PAIS VARCHAR(50) NOT NULL,
NUMERO INT,
RUA VARCHAR(50) NOT NULL,
CEP VARCHAR(9) NOT NULL,
TIPOS_ENDERECO_CODIGO INT NOT NULL,
CONSTRAINT FK_TIPOS_ENDERECO FOREIGN KEY (TIPOS_ENDERECO_CODIGO) REFERENCES TIPOS_ENDERECO(COD_END)
);

CREATE TABLE IF NOT EXISTS COMPONENTES (
ID_COMPONENTES INT PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
QUANTIDADE_ESTOQUE INT,
PRECO_UNITARIO DECIMAL(10, 2),
UNIDADE VARCHAR(50),
TIPOS_COMPONENTES_CODIGO INT,
CNPJ_FORNECEDOR VARCHAR(14),
CONSTRAINT FK_TIPOS_COMPONENTES FOREIGN KEY (TIPOS_COMPONENTES_CODIGO) REFERENCES TIPOS_COMPONENTE(COD_COMPONENTE),
CONSTRAINT FK_COMP_FORNECEDORES FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDORES(CNPJ)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
ID_PRODUTOS INT PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
COR VARCHAR(50),
DIMENSOES VARCHAR(100),
PESO DECIMAL(10, 2),
PRECO DECIMAL(10, 2),
TEMPO_FABRICACAO INT,
DESENHO_PRODUTO TEXT,
HORAS_MAO_OBRA INT
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS (
NUMERO INT PRIMARY KEY,
DATA_INCLUSAO DATE,
VALOR_TOTAL DECIMAL(10, 2),
VALOR_DESCONTO DECIMAL(10, 2),
VALOR_LIQUIDO DECIMAL(10, 2),
ID_FORMA_PAGAMENTO INT,
QUANTIDADE_PARCELAS INT,
ID_CLIENTES INT,
CONSTRAINT FK_ENCOMENDAS_CLIENTES FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(COD_CLIENTE)
);

CREATE TABLE IF NOT EXISTS MAQUINAS (
ID_MAQUINA INT PRIMARY KEY,
TEMPO_VIDA INT,
DATA_COMPRA DATE,
DATA_FIM_GARANTIA DATE
);

CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS (
ID_RECURSO INT PRIMARY KEY,
QUANTIDADE_NECESSARIA INT,
UNIDADE VARCHAR(50),
TEMPO_USO INT,
HORAS_MAO_OBRA INT,
ID_COD_PRODUTOS INT,
CONSTRAINT FK_RECURSOS_PRODUTOS FOREIGN KEY (ID_COD_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
);

CREATE TABLE IF NOT EXISTS RM (
ID_MANUTENCAO INT PRIMARY KEY,
DATA_MANUTENCAO DATE,
DESCRICAO TEXT,
ID_MAQUINA_COD INT,
CONSTRAINT FK_RM_MAQUINAS FOREIGN KEY (ID_MAQUINA_COD) REFERENCES MAQUINAS(ID_MAQUINA)
);

CREATE TABLE IF NOT EXISTS RS (
ID_SUPRIMENTO INT PRIMARY KEY,
QUANTIDADE INT,
DATA_NECESSIDADE DATE,
ID_COMPONENTES_COD INT,
CONSTRAINT FK_RS_COMPONENTES FOREIGN KEY (ID_COMPONENTES_COD) REFERENCES COMPONENTES(ID_COMPONENTES)
);

CREATE TABLE IF NOT EXISTS ENCOMENDA_PRODUTOS (
    ID_ENCOMENDA INT,
    ID_PRODUTO INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (ID_ENCOMENDA, ID_PRODUTO),
    CONSTRAINT FK_ENCOMENDA FOREIGN KEY (ID_ENCOMENDA) REFERENCES ENCOMENDAS(NUMERO),
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTOS)
);


#INICIO DAS ALTER TABLES!
ALTER TABLE EMPREGADOS ADD CNPJ_EMPRESA VARCHAR(14);
ALTER TABLE CLIENTES ADD COLUMN EMAIL VARCHAR(255);
ALTER TABLE EMPREGADOS MODIFY SALARIO_EMPREGADOS DECIMAL(12, 2);
ALTER TABLE EMPRESAS CHANGE RAZAO_SOCIAL RAZAO_SOCIAL_EMPRESA VARCHAR(255);
ALTER TABLE TIPOS_ENDERECO ADD CONSTRAINT UNIQUE (NOME);
ALTER TABLE TIPOS_COMPONENTE ADD COLUMN ATIVO BOOLEAN DEFAULT TRUE;
ALTER TABLE RS DROP COLUMN DATA_NECESSIDADE;
