DROP SCHEMA IF EXISTS EST_V;

CREATE SCHEMA EST_V;

USE EST_V;

CREATE TABLE IF NOT EXISTS CLIENTES (
CPF_CLI INT PRIMARY KEY,
NOME_CLI VARCHAR(45) NOT NULL,
NASC_CLI DATE,
STATUS_CLI ENUM('SIM', 'NÃO'),
CIDADE_CLI VARCHAR(50),
ESTADO_CLI VARCHAR(50),
PAIS_CLI VARCHAR(50),
PRIMARIA VARCHAR(10),
BAIRRO_CLI VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
ID_PRODUTO INT PRIMARY KEY,
NOME_PRODUTO VARCHAR(70) NOT NULL,
DIMENSOES_PRODUTO INT NOT NULL,
VALOR_PRODUTO INT NOT NULL,
DISP_PRODUTO ENUM('SIM', 'NAO'),
PROD_FORNECEDOR VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
ID_FORN INT PRIMARY KEY,
ENDERECO_FORN VARCHAR(100),
EMAIL_FORN VARCHAR(50),
TELEFONE_FORN VARCHAR(12),
CONTATO_FORN VARCHAR(100) NOT NULL,
PRODUTO_FORN VARCHAR(30) NOT NULL,
DESCRICAO_PRODUTO_FORN VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTOQUE (
ID_ESTOQUE INT PRIMARY KEY,
NOME_PRODUTO VARCHAR(50) NOT NULL,
LOC_PROD_ESTOQUE VARCHAR(100) NOT NULL,
QNT_PROD_ESTOQUE INT NOT NULL,
ID_PRODUTO INT,
CONSTRAINT FK_PRODUTO_E_ESTOQUE FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS VENDA (
ID_VENDA INT PRIMARY KEY,
PRODUTO_VENDA INT NOT NULL,
QNT_PRODUTO_VENDA INT NOT NULL,
ID_CLIENTE INT,
DATA_VENDA DATE,
PAGAMENTO_VENDA DECIMAL(12,2),
CONSTRAINT FK_CLIENTE_VENDA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CPF_CLI),
CONSTRAINT FK_PRODUTO_VENDA FOREIGN KEY (PRODUTO_VENDA) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
ID_PAGAMENTO INT PRIMARY KEY,
CLIENTE_PAGAMENTO INT,
DATA_PAGAMENTO DATE NOT NULL,
VALOR_PAGAMENTO INT NOT NULL,
SITUACAO_PAGAMENTO ENUM('PAGO', 'PENDENTE'),
ID_CLIENTE INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CPF_CLI)
);


CREATE TABLE IF NOT EXISTS CLIENTES_PRODUTOS (
ID_CLPR INT PRIMARY KEY AUTO_INCREMENT,
CPF_CLI INT NOT NULL,
ID_PRODUTO INT NOT NULL,
CONSTRAINT FK_E_CLIENTE FOREIGN KEY (CPF_CLI) REFERENCES CLIENTES(CPF_CLI),
CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS VENDA_PRODUTOS (
ID_VENDA INT,
ID_PRODUTO INT,
QNT_PRODUTO INT NOT NULL,
PRIMARY KEY (ID_VENDA, ID_PRODUTO),
CONSTRAINT FK_E_VENDA FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA),
CONSTRAINT FK_E_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);


ALTER TABLE CLIENTES 
ADD COLUMN TELEFONE_CLI VARCHAR(12);
ALTER TABLE CLIENTES 
ADD COLUMN ENDERECO_CLI VARCHAR(100);
ALTER TABLE CLIENTES 
DROP COLUMN PRIMARIA;
ALTER TABLE CLIENTES 
MODIFY COLUMN BAIRRO_CLI VARCHAR(100);


ALTER TABLE PRODUTOS 
ADD COLUMN DESCRICAO_PRODUTO TEXT;
ALTER TABLE PRODUTOS 
ADD COLUMN COR_PRODUTO VARCHAR(20);
ALTER TABLE PRODUTOS 
DROP COLUMN DISP_PRODUTO;
ALTER TABLE PRODUTOS 
MODIFY COLUMN VALOR_PRODUTO DECIMAL(12, 2);


ALTER TABLE FORNECEDORES 
ADD COLUMN CNPJ VARCHAR(11) NOT NULL;
ALTER TABLE FORNECEDORES 
DROP COLUMN TELEFONE_FORN;
ALTER TABLE FORNECEDORES 
MODIFY COLUMN CONTATO_FORN VARCHAR(100);
ALTER TABLE FORNECEDORES 
CHANGE COLUMN DESCRICAO_PRODUTO_FORN DESCRICAO_PRODUTO_FORN VARCHAR(100);


ALTER TABLE ESTOQUE 
ADD COLUMN DATA_RECEBIMENTO DATE;
ALTER TABLE ESTOQUE 
DROP COLUMN QNT_PROD_ESTOQUE;
ALTER TABLE ESTOQUE 
MODIFY COLUMN LOC_PROD_ESTOQUE VARCHAR(100);
ALTER TABLE ESTOQUE 
CHANGE COLUMN NOME_PRODUTO NOME_PRODUTO VARCHAR(50);


ALTER TABLE VENDA 
ADD COLUMN VALOR_TOTAL DECIMAL(12, 2);
ALTER TABLE VENDA 
DROP COLUMN PAGAMENTO_VENDA;
ALTER TABLE VENDA 
MODIFY COLUMN QNT_PRODUTO_VENDA INT NOT NULL;
ALTER TABLE VENDA 
CHANGE COLUMN ID_CLIENTE ID_CLIENTE INT;


ALTER TABLE PAGAMENTOS 
ADD COLUMN TIPO_PAGAMENTO ENUM('cartao', 'boleto', 'dinheiro');
ALTER TABLE PAGAMENTOS 
DROP COLUMN CLIENTE_PAGAMENTO;
ALTER TABLE PAGAMENTOS 
MODIFY COLUMN VALOR_PAGAMENTO DECIMAL(12, 2);
ALTER TABLE PAGAMENTOS 
CHANGE COLUMN SITUACAO_PAGAMENTO STATUS_PAGAMENTO ENUM('pago', 'pendente');
